gpus: [2]
get_pb: true
get_fea: true
use_rerank: false
save_badcase: false
use_old_name: false

height: 384
batch_size: 256

model_config:
  name: cacenet
  train_mode: false
  local_conv_out_channels: 768
  triplet_type: stripe
  num_layers: 50
  last_conv_stride: 1
  dropout_place: after
  margin: 0.5
  pooling_types: [avg, max]
  non_local_type: single
  compression: 16
  with_pair_triplet: true
  alpha: 0.9

flip: true
root_path: your_path
pretrain_task: cacenet
pretrain_model_step: 32400 #64720 82640 163120
eval_dataset:  dataset_path #Duke_pcb  #Duke_pcb #market1501 cuhk03_split2_pcb




